version: '3'
services:
  redis:
    image: redis
    container_name: dotabackseater-redis
    ports:
      - "6379:6379"  # Exposes Redis to the host machine (optional)
    networks:
      - dotabackseater-network

  go-server:
    image: dotabackseaterbackend
    container_name: dotabackseaterbackend
    ports:
      - "443:443"  # Exposes the Go server to the host machine
    networks:
      - dotabackseater-network
    volumes:
      - /etc/letsencrypt/live/dotabackseater.ruvice.com:/certs:ro
    depends_on:
      - redis  # Ensures Redis starts before the Go server

networks:
  dotabackseater-network:
    driver: bridge